# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
 branches:
   include:
   - main # Only run on changes to main

pr:
 branches:
   exclude:
   - '*' # Never run when a PR is created, we'll have a separate quality pipeline for PRs

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: NugetToolInstaller@1
      displayName: Install Nuget tool
    
    - task: NugetCommand@2
      displayName: Restore Nuget packages
      inputs:
        restoreSolution: '$(solution)'
    
    - task: VSBuild@1
      displayName: Build solution
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: VSTest@2
      displayName: Run unit tests
      inputs:
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
    
    - task: AzureCLI@2
      displayName: Build Bicep template
      inputs:
       azureSubscription: AIRS
       scriptType: ps
       scriptLocation: inlineScript
       inlineScript: |
         az bicep install
         az bicep build -f $(Build.SourcesDirectory)\infrastructure\main.bicep
         mkdir $(Build.ArtifactStagingDirectory)\infrastructure\
         copy $(Build.SourcesDirectory)\infrastructure\main.* $(Build.ArtifactStagingDirectory)\infrastructure\

    - task: PublishPipelineArtifact@1
      displayName: Publish web app artifact
      inputs:
       targetPath: $(Build.ArtifactStagingDirectory)\GovtReportingDemo.zip
       artifact: webApp
       publishLocation: pipeline

    - task: PublishPipelineArtifact@1
      displayName: Publish infrastructure artifact
      inputs:
       targetPath: $(Build.ArtifactStagingDirectory)\infrastructure\
       artifact: infrastructure
       publishLocation: pipeline

- template: templates/deploy-template.yaml
  parameters:
    stageName: DeployDevelopment
    environmentName: govt-rpt-dev
    variableGroupName: GOVT-REPORTING-DEV
    serviceConnection: AIRS